### ISSUE TITLE
Leaked Token

### ISSUE THREAD

**Issue by SourSpoon** [Norgesnerd/kewl-bot#1]
https://github.com/Norgesnerd/kewl-bot/blob/cacb8dc2bc91c22108b38c017c7afa552b27b6e9/bot.py#L94

#You leaked your token! This gives anyone full access to your bot.
https://discordapp.com/developers/applications/me

Please leverage a config file of some kind and add the config to a gitignore

**Comment by Norgesnerd** [comment]
Damn, I forgot! Thanks for telling me :)
